/** Launch Kit v2 — Enhanced launch kit with agent orchestration + CLAUDE.md generation */

import {
  PROJECT_TYPES,
  TECH_CATEGORIES,
  DEFAULT_TECH_CHOICES,
  DEPLOY_TARGETS,
  PLATFORM_OPTIONS,
  MOBILE_FRAMEWORK_OPTIONS,
  type LaunchKitDraft,
  type ProjectType,
  type TechChoice,
  type TeamRole,
  generatePlan,
  generateWhitepaper,
} from "./launch-kit";

export type AgentOrchestratorConfig = {
  orchestratorModel: string;
  maxConcurrentAgents: number;
  consensusRequired: boolean;
  autoConsultOnPR: boolean;
  autoConsultOnDeploy: boolean;
  weeklyRetroEnabled: boolean;
};

export type LaunchKitV2Draft = LaunchKitDraft & {
  orchestrator: AgentOrchestratorConfig;
  claudeMdTemplate: string;
  vibeCodeReady: boolean;
  repoUrl: string;
};

export const DEFAULT_ORCHESTRATOR: AgentOrchestratorConfig = {
  orchestratorModel: "claude-sonnet-4-6",
  maxConcurrentAgents: 3,
  consensusRequired: true,
  autoConsultOnPR: true,
  autoConsultOnDeploy: false,
  weeklyRetroEnabled: true,
};

export const EMPTY_LAUNCH_KIT_V2: LaunchKitV2Draft = {
  projectName: "",
  projectType: null,
  description: "",
  targetUser: "",
  problem: "",
  platforms: [],
  mvpFeatures: [],
  comparables: [],
  team: [],
  consensus: {
    ceoIndex: null,
    confidenceLevels: {},
    phaseAuthority: {},
    consensusThreshold: 67,
  },
  grillQuestions: [],
  grillCompleted: false,
  grillSkipped: false,
  deployTarget: "web_ios_android",
  techChoices: [...DEFAULT_TECH_CHOICES],
  mobileFramework: "React Native / Expo",
  buildPhases: [
    { phase: "Foundation", features: [] },
    { phase: "Core Feature 1", features: [] },
    { phase: "Core Feature 2", features: [] },
    { phase: "Polish & Launch", features: [] },
  ],
  planGenerated: false,
  northStar: "",
  whitepaper: "",
  orchestrator: { ...DEFAULT_ORCHESTRATOR },
  claudeMdTemplate: "",
  vibeCodeReady: false,
  repoUrl: "",
};

export const ORCHESTRATOR_MODELS = [
  { id: "claude-opus-4-6", label: "Claude Opus 4.6", description: "Best reasoning, highest quality" },
  { id: "claude-sonnet-4-6", label: "Claude Sonnet 4.6", description: "Fast + capable (recommended)" },
  { id: "claude-haiku-4-5", label: "Claude Haiku 4.5", description: "Fastest, best for simple tasks" },
];

export function generateClaudeMd(draft: LaunchKitV2Draft): string {
  const lines: string[] = [];

  lines.push(`# ${draft.projectName || "Project"} — Agent Instructions\n`);
  lines.push(`> Generated by Persona Builder Launch Kit v2\n`);

  lines.push("## Project Overview\n");
  if (draft.description) lines.push(draft.description + "\n");
  if (draft.targetUser) lines.push(`**Target User:** ${draft.targetUser}\n`);
  if (draft.problem) lines.push(`**Problem:** ${draft.problem}\n`);

  // Tech stack
  if (draft.techChoices.length > 0) {
    lines.push("## Tech Stack\n");
    draft.techChoices.forEach((tc) => {
      const cat = TECH_CATEGORIES.find((c) => c.id === tc.category);
      lines.push(`- **${cat?.label || tc.category}:** ${tc.choice}`);
    });
    lines.push("");
  }

  // Persona team
  if (draft.team.length > 0) {
    lines.push("## Persona Team\n");
    lines.push("Consult the relevant persona at every major decision. Reference `docs/personas/` for full profiles.\n");
    lines.push("| Role | Modeled After | Focus |");
    lines.push("|------|---------------|-------|");
    draft.team.forEach((t) => {
      lines.push(`| ${t.role} | ${t.company || "—"} | ${t.focus || "—"} |`);
    });
    lines.push("");
  }

  // Consultation rules
  lines.push("## Consultation Rules\n");
  lines.push("1. **Feature Planning:** Consult Product Lead + domain persona");
  lines.push("2. **Implementation Review:** Consult relevant domain persona");
  lines.push("3. **Integration Check:** Consult 2-3 personas + use Consensus Protocol");
  lines.push("4. **Deadlock Resolution:** CEO Tiebreaker (weighted evaluation)");
  lines.push("5. **User Override:** User always has final say\n");

  // Orchestrator config
  lines.push("## Agent Orchestration\n");
  lines.push(`- **Orchestrator Model:** ${draft.orchestrator.orchestratorModel}`);
  lines.push(`- **Max Concurrent Agents:** ${draft.orchestrator.maxConcurrentAgents}`);
  lines.push(`- **Consensus Required:** ${draft.orchestrator.consensusRequired ? "Yes (2/3 majority)" : "No"}`);
  lines.push(`- **Auto-consult on PR:** ${draft.orchestrator.autoConsultOnPR ? "Yes" : "No"}`);
  lines.push(`- **Auto-consult on Deploy:** ${draft.orchestrator.autoConsultOnDeploy ? "Yes" : "No"}`);
  lines.push(`- **Weekly Retros:** ${draft.orchestrator.weeklyRetroEnabled ? "Enabled" : "Disabled"}\n`);

  // Build phases
  if (draft.buildPhases.some((p) => p.features.length > 0)) {
    lines.push("## Build Roadmap\n");
    draft.buildPhases.forEach((phase, i) => {
      lines.push(`### Phase ${i + 1}: ${phase.phase}`);
      phase.features.forEach((f) => lines.push(`- ${f}`));
      lines.push("");
    });
  }

  // North star
  if (draft.northStar) {
    lines.push(`## North Star\n\n${draft.northStar}\n`);
  }

  lines.push("---\n");
  lines.push(`*Generated by Persona Builder on ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}

export {
  PROJECT_TYPES,
  TECH_CATEGORIES,
  DEFAULT_TECH_CHOICES,
  DEPLOY_TARGETS,
  PLATFORM_OPTIONS,
  MOBILE_FRAMEWORK_OPTIONS,
  generatePlan,
  generateWhitepaper,
};
export type { ProjectType, TechChoice, TeamRole };
