/** VibeCode — Generate vibe-coded project scaffolds with persona-driven instructions */

export type VibeCodeFramework = {
  id: string;
  label: string;
  description: string;
  scaffoldCommand: string;
};

export const VIBECODE_FRAMEWORKS: VibeCodeFramework[] = [
  { id: "nextjs", label: "Next.js", description: "React framework with App Router", scaffoldCommand: "npx create-next-app@latest {{name}} --typescript --tailwind --eslint --app --src-dir" },
  { id: "react_vite", label: "React + Vite", description: "Fast React SPA with Vite", scaffoldCommand: "npm create vite@latest {{name}} -- --template react-ts" },
  { id: "expo", label: "Expo (React Native)", description: "Cross-platform mobile + web", scaffoldCommand: "npx create-expo-app {{name}} --template tabs" },
  { id: "python_fastapi", label: "Python FastAPI", description: "Modern Python API server", scaffoldCommand: "pip install fastapi uvicorn && mkdir {{name}} && cd {{name}}" },
  { id: "svelte", label: "SvelteKit", description: "Svelte full-stack framework", scaffoldCommand: "npx sv create {{name}}" },
  { id: "remix", label: "Remix", description: "React framework with loaders", scaffoldCommand: "npx create-remix@latest {{name}}" },
];

export type VibeCodeStyle = {
  id: string;
  label: string;
  description: string;
  principles: string[];
};

export const VIBECODE_STYLES: VibeCodeStyle[] = [
  {
    id: "move_fast",
    label: "Move Fast",
    description: "Ship first, polish later. Optimize for learning speed.",
    principles: ["Prefer simple solutions over clever ones", "Ship daily, measure weekly", "Delete code instead of commenting it out", "Use the framework defaults"],
  },
  {
    id: "production_grade",
    label: "Production Grade",
    description: "Enterprise-ready from day one. Tests, types, docs.",
    principles: ["100% TypeScript strict mode", "Unit tests for business logic", "Integration tests for API routes", "Document all public interfaces"],
  },
  {
    id: "creative_prototype",
    label: "Creative Prototype",
    description: "Explore and experiment. Visual-first, playful.",
    principles: ["Prioritize the demo experience", "Use animations and transitions freely", "Optimize for 'wow factor'", "Hardcode when it saves time"],
  },
  {
    id: "minimal",
    label: "Minimal",
    description: "Less is more. Fewer dependencies, smaller bundle.",
    principles: ["No dependency unless absolutely necessary", "Prefer platform APIs over libraries", "Keep bundle under 100KB", "One way to do each thing"],
  },
];

export type VibeCodeDraft = {
  projectName: string;
  framework: VibeCodeFramework | null;
  style: VibeCodeStyle | null;
  description: string;
  features: string[];
  personaTeamMd: string; // pasted or generated team.md content
  usePersonaTeam: boolean;
  claudeMdContent: string;
  scaffoldCommand: string;
  extraInstructions: string;
};

export const EMPTY_VIBECODE_DRAFT: VibeCodeDraft = {
  projectName: "",
  framework: null,
  style: null,
  description: "",
  features: [],
  personaTeamMd: "",
  usePersonaTeam: false,
  claudeMdContent: "",
  scaffoldCommand: "",
  extraInstructions: "",
};

export function generateVibeCodeClaudeMd(draft: VibeCodeDraft): string {
  const lines: string[] = [];

  lines.push(`# ${draft.projectName || "Project"}\n`);

  if (draft.description) {
    lines.push(draft.description + "\n");
  }

  // Framework
  if (draft.framework) {
    lines.push(`## Framework: ${draft.framework.label}\n`);
    lines.push(`${draft.framework.description}\n`);
  }

  // Vibe / Style
  if (draft.style) {
    lines.push(`## Vibe: ${draft.style.label}\n`);
    lines.push(`${draft.style.description}\n`);
    lines.push("### Coding Principles\n");
    draft.style.principles.forEach((p) => lines.push(`- ${p}`));
    lines.push("");
  }

  // Features
  if (draft.features.length > 0) {
    lines.push("## Features to Build\n");
    draft.features.forEach((f, i) => lines.push(`${i + 1}. ${f}`));
    lines.push("");
  }

  // Extra instructions
  if (draft.extraInstructions) {
    lines.push("## Additional Instructions\n");
    lines.push(draft.extraInstructions + "\n");
  }

  // Persona team
  if (draft.usePersonaTeam && draft.personaTeamMd) {
    lines.push("---\n");
    lines.push("## Persona Team\n");
    lines.push(draft.personaTeamMd);
    lines.push("");
  }

  lines.push("---\n");
  lines.push(`*Generated by VibeCode on ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}

export function generateScaffoldCommand(draft: VibeCodeDraft): string {
  if (!draft.framework || !draft.projectName) return "";
  return draft.framework.scaffoldCommand.replace(/\{\{name\}\}/g, draft.projectName.toLowerCase().replace(/\s+/g, "-"));
}
